/* 
 * order
 *
 * Enables omni-channel persistence and interaction for selling contexts.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace FraudAPI.Model.Order
{
    /// <summary>
    /// The result of a find operation on the orders resource.
    /// </summary>
    [DataContract]
    public partial class FindOrdersResult :  IEquatable<FindOrdersResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindOrdersResult" /> class.
        /// </summary>
        /// <param name="LastPage">Indicates whether the return page is last..</param>
        /// <param name="PageNumber">Number of the returned page..</param>
        /// <param name="TotalPages">The total number of result pages available.</param>
        /// <param name="TotalResults">The total number of results available.</param>
        /// <param name="PageContent">List of orders that matches the find criteria, limited by pageSize..</param>
        public FindOrdersResult(bool? LastPage = default(bool?), int? PageNumber = default(int?), long? TotalPages = default(long?), long? TotalResults = default(long?), List<OrderViewData> PageContent = default(List<OrderViewData>))
        {
            this.LastPage = LastPage;
            this.PageNumber = PageNumber;
            this.TotalPages = TotalPages;
            this.TotalResults = TotalResults;
            this.PageContent = PageContent;
        }
        
        /// <summary>
        /// Indicates whether the return page is last.
        /// </summary>
        /// <value>Indicates whether the return page is last.</value>
        [DataMember(Name="lastPage", EmitDefaultValue=false)]
        public bool? LastPage { get; set; }

        /// <summary>
        /// Number of the returned page.
        /// </summary>
        /// <value>Number of the returned page.</value>
        [DataMember(Name="pageNumber", EmitDefaultValue=false)]
        public int? PageNumber { get; set; }

        /// <summary>
        /// The total number of result pages available
        /// </summary>
        /// <value>The total number of result pages available</value>
        [DataMember(Name="totalPages", EmitDefaultValue=false)]
        public long? TotalPages { get; set; }

        /// <summary>
        /// The total number of results available
        /// </summary>
        /// <value>The total number of results available</value>
        [DataMember(Name="totalResults", EmitDefaultValue=false)]
        public long? TotalResults { get; set; }

        /// <summary>
        /// List of orders that matches the find criteria, limited by pageSize.
        /// </summary>
        /// <value>List of orders that matches the find criteria, limited by pageSize.</value>
        [DataMember(Name="pageContent", EmitDefaultValue=false)]
        public List<OrderViewData> PageContent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindOrdersResult {\n");
            sb.Append("  LastPage: ").Append(LastPage).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  TotalResults: ").Append(TotalResults).Append("\n");
            sb.Append("  PageContent: ").Append(PageContent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindOrdersResult);
        }

        /// <summary>
        /// Returns true if FindOrdersResult instances are equal
        /// </summary>
        /// <param name="input">Instance of FindOrdersResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindOrdersResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LastPage == input.LastPage ||
                    (this.LastPage != null &&
                    this.LastPage.Equals(input.LastPage))
                ) && 
                (
                    this.PageNumber == input.PageNumber ||
                    (this.PageNumber != null &&
                    this.PageNumber.Equals(input.PageNumber))
                ) && 
                (
                    this.TotalPages == input.TotalPages ||
                    (this.TotalPages != null &&
                    this.TotalPages.Equals(input.TotalPages))
                ) && 
                (
                    this.TotalResults == input.TotalResults ||
                    (this.TotalResults != null &&
                    this.TotalResults.Equals(input.TotalResults))
                ) && 
                (
                    this.PageContent == input.PageContent ||
                    this.PageContent != null &&
                    this.PageContent.SequenceEqual(input.PageContent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastPage != null)
                    hashCode = hashCode * 59 + this.LastPage.GetHashCode();
                if (this.PageNumber != null)
                    hashCode = hashCode * 59 + this.PageNumber.GetHashCode();
                if (this.TotalPages != null)
                    hashCode = hashCode * 59 + this.TotalPages.GetHashCode();
                if (this.TotalResults != null)
                    hashCode = hashCode * 59 + this.TotalResults.GetHashCode();
                if (this.PageContent != null)
                    hashCode = hashCode * 59 + this.PageContent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TotalPages (long?) minimum
            if(this.TotalPages < (long?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TotalPages, must be a value greater than or equal to 0.", new [] { "TotalPages" });
            }

            // TotalResults (long?) minimum
            if(this.TotalResults < (long?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TotalResults, must be a value greater than or equal to 0.", new [] { "TotalResults" });
            }

            yield break;
        }
    }

}
