/* 
 * order
 *
 * Enables omni-channel persistence and interaction for selling contexts.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace FraudAPI.Model.Order
{
    /// <summary>
    /// JsonNode
    /// </summary>
    [DataContract]
    public partial class JsonNode :  IEquatable<JsonNode>, IValidatableObject
    {
        /// <summary>
        /// Defines NodeType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NodeTypeEnum
        {
            
            /// <summary>
            /// Enum ARRAY for value: ARRAY
            /// </summary>
            [EnumMember(Value = "ARRAY")]
            ARRAY = 1,
            
            /// <summary>
            /// Enum BINARY for value: BINARY
            /// </summary>
            [EnumMember(Value = "BINARY")]
            BINARY = 2,
            
            /// <summary>
            /// Enum BOOLEAN for value: BOOLEAN
            /// </summary>
            [EnumMember(Value = "BOOLEAN")]
            BOOLEAN = 3,
            
            /// <summary>
            /// Enum MISSING for value: MISSING
            /// </summary>
            [EnumMember(Value = "MISSING")]
            MISSING = 4,
            
            /// <summary>
            /// Enum NULL for value: NULL
            /// </summary>
            [EnumMember(Value = "NULL")]
            NULL = 5,
            
            /// <summary>
            /// Enum NUMBER for value: NUMBER
            /// </summary>
            [EnumMember(Value = "NUMBER")]
            NUMBER = 6,
            
            /// <summary>
            /// Enum OBJECT for value: OBJECT
            /// </summary>
            [EnumMember(Value = "OBJECT")]
            OBJECT = 7,
            
            /// <summary>
            /// Enum POJO for value: POJO
            /// </summary>
            [EnumMember(Value = "POJO")]
            POJO = 8,
            
            /// <summary>
            /// Enum STRING for value: STRING
            /// </summary>
            [EnumMember(Value = "STRING")]
            STRING = 9
        }

        /// <summary>
        /// Gets or Sets NodeType
        /// </summary>
        [DataMember(Name="nodeType", EmitDefaultValue=false)]
        public NodeTypeEnum? NodeType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonNode" /> class.
        /// </summary>
        /// <param name="_Float">_Float.</param>
        /// <param name="ValueNode">ValueNode.</param>
        /// <param name="ContainerNode">ContainerNode.</param>
        /// <param name="MissingNode">MissingNode.</param>
        /// <param name="_Object">_Object.</param>
        /// <param name="NodeType">NodeType.</param>
        /// <param name="Pojo">Pojo.</param>
        /// <param name="Number">Number.</param>
        /// <param name="IntegralNumber">IntegralNumber.</param>
        /// <param name="FloatingPointNumber">FloatingPointNumber.</param>
        /// <param name="_Short">_Short.</param>
        /// <param name="_Int">_Int.</param>
        /// <param name="_Long">_Long.</param>
        /// <param name="_Double">_Double.</param>
        /// <param name="BigDecimal">BigDecimal.</param>
        /// <param name="BigInteger">BigInteger.</param>
        /// <param name="Textual">Textual.</param>
        /// <param name="Boolean">Boolean.</param>
        /// <param name="Binary">Binary.</param>
        /// <param name="Array">Array.</param>
        /// <param name="_Null">_Null.</param>
        public JsonNode(bool? _Float = default(bool?), bool? ValueNode = default(bool?), bool? ContainerNode = default(bool?), bool? MissingNode = default(bool?), bool? _Object = default(bool?), NodeTypeEnum? NodeType = default(NodeTypeEnum?), bool? Pojo = default(bool?), bool? Number = default(bool?), bool? IntegralNumber = default(bool?), bool? FloatingPointNumber = default(bool?), bool? _Short = default(bool?), bool? _Int = default(bool?), bool? _Long = default(bool?), bool? _Double = default(bool?), bool? BigDecimal = default(bool?), bool? BigInteger = default(bool?), bool? Textual = default(bool?), bool? Boolean = default(bool?), bool? Binary = default(bool?), bool? Array = default(bool?), bool? _Null = default(bool?))
        {
            this._Float = _Float;
            this.ValueNode = ValueNode;
            this.ContainerNode = ContainerNode;
            this.MissingNode = MissingNode;
            this._Object = _Object;
            this.NodeType = NodeType;
            this.Pojo = Pojo;
            this.Number = Number;
            this.IntegralNumber = IntegralNumber;
            this.FloatingPointNumber = FloatingPointNumber;
            this._Short = _Short;
            this._Int = _Int;
            this._Long = _Long;
            this._Double = _Double;
            this.BigDecimal = BigDecimal;
            this.BigInteger = BigInteger;
            this.Textual = Textual;
            this.Boolean = Boolean;
            this.Binary = Binary;
            this.Array = Array;
            this._Null = _Null;
        }
        
        /// <summary>
        /// Gets or Sets _Float
        /// </summary>
        [DataMember(Name="float", EmitDefaultValue=false)]
        public bool? _Float { get; set; }

        /// <summary>
        /// Gets or Sets ValueNode
        /// </summary>
        [DataMember(Name="valueNode", EmitDefaultValue=false)]
        public bool? ValueNode { get; set; }

        /// <summary>
        /// Gets or Sets ContainerNode
        /// </summary>
        [DataMember(Name="containerNode", EmitDefaultValue=false)]
        public bool? ContainerNode { get; set; }

        /// <summary>
        /// Gets or Sets MissingNode
        /// </summary>
        [DataMember(Name="missingNode", EmitDefaultValue=false)]
        public bool? MissingNode { get; set; }

        /// <summary>
        /// Gets or Sets _Object
        /// </summary>
        [DataMember(Name="object", EmitDefaultValue=false)]
        public bool? _Object { get; set; }


        /// <summary>
        /// Gets or Sets Pojo
        /// </summary>
        [DataMember(Name="pojo", EmitDefaultValue=false)]
        public bool? Pojo { get; set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public bool? Number { get; set; }

        /// <summary>
        /// Gets or Sets IntegralNumber
        /// </summary>
        [DataMember(Name="integralNumber", EmitDefaultValue=false)]
        public bool? IntegralNumber { get; set; }

        /// <summary>
        /// Gets or Sets FloatingPointNumber
        /// </summary>
        [DataMember(Name="floatingPointNumber", EmitDefaultValue=false)]
        public bool? FloatingPointNumber { get; set; }

        /// <summary>
        /// Gets or Sets _Short
        /// </summary>
        [DataMember(Name="short", EmitDefaultValue=false)]
        public bool? _Short { get; set; }

        /// <summary>
        /// Gets or Sets _Int
        /// </summary>
        [DataMember(Name="int", EmitDefaultValue=false)]
        public bool? _Int { get; set; }

        /// <summary>
        /// Gets or Sets _Long
        /// </summary>
        [DataMember(Name="long", EmitDefaultValue=false)]
        public bool? _Long { get; set; }

        /// <summary>
        /// Gets or Sets _Double
        /// </summary>
        [DataMember(Name="double", EmitDefaultValue=false)]
        public bool? _Double { get; set; }

        /// <summary>
        /// Gets or Sets BigDecimal
        /// </summary>
        [DataMember(Name="bigDecimal", EmitDefaultValue=false)]
        public bool? BigDecimal { get; set; }

        /// <summary>
        /// Gets or Sets BigInteger
        /// </summary>
        [DataMember(Name="bigInteger", EmitDefaultValue=false)]
        public bool? BigInteger { get; set; }

        /// <summary>
        /// Gets or Sets Textual
        /// </summary>
        [DataMember(Name="textual", EmitDefaultValue=false)]
        public bool? Textual { get; set; }

        /// <summary>
        /// Gets or Sets Boolean
        /// </summary>
        [DataMember(Name="boolean", EmitDefaultValue=false)]
        public bool? Boolean { get; set; }

        /// <summary>
        /// Gets or Sets Binary
        /// </summary>
        [DataMember(Name="binary", EmitDefaultValue=false)]
        public bool? Binary { get; set; }

        /// <summary>
        /// Gets or Sets Array
        /// </summary>
        [DataMember(Name="array", EmitDefaultValue=false)]
        public bool? Array { get; set; }

        /// <summary>
        /// Gets or Sets _Null
        /// </summary>
        [DataMember(Name="null", EmitDefaultValue=false)]
        public bool? _Null { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonNode {\n");
            sb.Append("  _Float: ").Append(_Float).Append("\n");
            sb.Append("  ValueNode: ").Append(ValueNode).Append("\n");
            sb.Append("  ContainerNode: ").Append(ContainerNode).Append("\n");
            sb.Append("  MissingNode: ").Append(MissingNode).Append("\n");
            sb.Append("  _Object: ").Append(_Object).Append("\n");
            sb.Append("  NodeType: ").Append(NodeType).Append("\n");
            sb.Append("  Pojo: ").Append(Pojo).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  IntegralNumber: ").Append(IntegralNumber).Append("\n");
            sb.Append("  FloatingPointNumber: ").Append(FloatingPointNumber).Append("\n");
            sb.Append("  _Short: ").Append(_Short).Append("\n");
            sb.Append("  _Int: ").Append(_Int).Append("\n");
            sb.Append("  _Long: ").Append(_Long).Append("\n");
            sb.Append("  _Double: ").Append(_Double).Append("\n");
            sb.Append("  BigDecimal: ").Append(BigDecimal).Append("\n");
            sb.Append("  BigInteger: ").Append(BigInteger).Append("\n");
            sb.Append("  Textual: ").Append(Textual).Append("\n");
            sb.Append("  Boolean: ").Append(Boolean).Append("\n");
            sb.Append("  Binary: ").Append(Binary).Append("\n");
            sb.Append("  Array: ").Append(Array).Append("\n");
            sb.Append("  _Null: ").Append(_Null).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonNode);
        }

        /// <summary>
        /// Returns true if JsonNode instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonNode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonNode input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Float == input._Float ||
                    (this._Float != null &&
                    this._Float.Equals(input._Float))
                ) && 
                (
                    this.ValueNode == input.ValueNode ||
                    (this.ValueNode != null &&
                    this.ValueNode.Equals(input.ValueNode))
                ) && 
                (
                    this.ContainerNode == input.ContainerNode ||
                    (this.ContainerNode != null &&
                    this.ContainerNode.Equals(input.ContainerNode))
                ) && 
                (
                    this.MissingNode == input.MissingNode ||
                    (this.MissingNode != null &&
                    this.MissingNode.Equals(input.MissingNode))
                ) && 
                (
                    this._Object == input._Object ||
                    (this._Object != null &&
                    this._Object.Equals(input._Object))
                ) && 
                (
                    this.NodeType == input.NodeType ||
                    (this.NodeType != null &&
                    this.NodeType.Equals(input.NodeType))
                ) && 
                (
                    this.Pojo == input.Pojo ||
                    (this.Pojo != null &&
                    this.Pojo.Equals(input.Pojo))
                ) && 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.IntegralNumber == input.IntegralNumber ||
                    (this.IntegralNumber != null &&
                    this.IntegralNumber.Equals(input.IntegralNumber))
                ) && 
                (
                    this.FloatingPointNumber == input.FloatingPointNumber ||
                    (this.FloatingPointNumber != null &&
                    this.FloatingPointNumber.Equals(input.FloatingPointNumber))
                ) && 
                (
                    this._Short == input._Short ||
                    (this._Short != null &&
                    this._Short.Equals(input._Short))
                ) && 
                (
                    this._Int == input._Int ||
                    (this._Int != null &&
                    this._Int.Equals(input._Int))
                ) && 
                (
                    this._Long == input._Long ||
                    (this._Long != null &&
                    this._Long.Equals(input._Long))
                ) && 
                (
                    this._Double == input._Double ||
                    (this._Double != null &&
                    this._Double.Equals(input._Double))
                ) && 
                (
                    this.BigDecimal == input.BigDecimal ||
                    (this.BigDecimal != null &&
                    this.BigDecimal.Equals(input.BigDecimal))
                ) && 
                (
                    this.BigInteger == input.BigInteger ||
                    (this.BigInteger != null &&
                    this.BigInteger.Equals(input.BigInteger))
                ) && 
                (
                    this.Textual == input.Textual ||
                    (this.Textual != null &&
                    this.Textual.Equals(input.Textual))
                ) && 
                (
                    this.Boolean == input.Boolean ||
                    (this.Boolean != null &&
                    this.Boolean.Equals(input.Boolean))
                ) && 
                (
                    this.Binary == input.Binary ||
                    (this.Binary != null &&
                    this.Binary.Equals(input.Binary))
                ) && 
                (
                    this.Array == input.Array ||
                    (this.Array != null &&
                    this.Array.Equals(input.Array))
                ) && 
                (
                    this._Null == input._Null ||
                    (this._Null != null &&
                    this._Null.Equals(input._Null))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Float != null)
                    hashCode = hashCode * 59 + this._Float.GetHashCode();
                if (this.ValueNode != null)
                    hashCode = hashCode * 59 + this.ValueNode.GetHashCode();
                if (this.ContainerNode != null)
                    hashCode = hashCode * 59 + this.ContainerNode.GetHashCode();
                if (this.MissingNode != null)
                    hashCode = hashCode * 59 + this.MissingNode.GetHashCode();
                if (this._Object != null)
                    hashCode = hashCode * 59 + this._Object.GetHashCode();
                if (this.NodeType != null)
                    hashCode = hashCode * 59 + this.NodeType.GetHashCode();
                if (this.Pojo != null)
                    hashCode = hashCode * 59 + this.Pojo.GetHashCode();
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.IntegralNumber != null)
                    hashCode = hashCode * 59 + this.IntegralNumber.GetHashCode();
                if (this.FloatingPointNumber != null)
                    hashCode = hashCode * 59 + this.FloatingPointNumber.GetHashCode();
                if (this._Short != null)
                    hashCode = hashCode * 59 + this._Short.GetHashCode();
                if (this._Int != null)
                    hashCode = hashCode * 59 + this._Int.GetHashCode();
                if (this._Long != null)
                    hashCode = hashCode * 59 + this._Long.GetHashCode();
                if (this._Double != null)
                    hashCode = hashCode * 59 + this._Double.GetHashCode();
                if (this.BigDecimal != null)
                    hashCode = hashCode * 59 + this.BigDecimal.GetHashCode();
                if (this.BigInteger != null)
                    hashCode = hashCode * 59 + this.BigInteger.GetHashCode();
                if (this.Textual != null)
                    hashCode = hashCode * 59 + this.Textual.GetHashCode();
                if (this.Boolean != null)
                    hashCode = hashCode * 59 + this.Boolean.GetHashCode();
                if (this.Binary != null)
                    hashCode = hashCode * 59 + this.Binary.GetHashCode();
                if (this.Array != null)
                    hashCode = hashCode * 59 + this.Array.GetHashCode();
                if (this._Null != null)
                    hashCode = hashCode * 59 + this._Null.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
