/* 
 * order
 *
 * Enables omni-channel persistence and interaction for selling contexts.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace FraudAPI.Model.Order
{
    /// <summary>
    /// Response containing all versions of the specified order
    /// </summary>
    [DataContract]
    public partial class OrderVersionsResponse :  IEquatable<OrderVersionsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderVersionsResponse" /> class.
        /// </summary>
        /// <param name="OrderId">Order ID.</param>
        /// <param name="Versions">List of order version objects.</param>
        /// <param name="TotalResults">The total count of unacknowledged orders for the specified enterprise unit id.</param>
        /// <param name="TotalPages">The total number of pages.</param>
        /// <param name="PageNumber">The page number of the response.</param>
        /// <param name="LastPage">Last page indicator.</param>
        /// <param name="SourceOrganization">The organization that originally created the order.</param>
        public OrderVersionsResponse(string OrderId = default(string), List<OrderVersionResponse> Versions = default(List<OrderVersionResponse>), long? TotalResults = default(long?), int? TotalPages = default(int?), int? PageNumber = default(int?), bool? LastPage = default(bool?), string SourceOrganization = default(string))
        {
            this.OrderId = OrderId;
            this.Versions = Versions;
            this.TotalResults = TotalResults;
            this.TotalPages = TotalPages;
            this.PageNumber = PageNumber;
            this.LastPage = LastPage;
            this.SourceOrganization = SourceOrganization;
        }
        
        /// <summary>
        /// Order ID
        /// </summary>
        /// <value>Order ID</value>
        [DataMember(Name="orderId", EmitDefaultValue=false)]
        public string OrderId { get; set; }

        /// <summary>
        /// List of order version objects
        /// </summary>
        /// <value>List of order version objects</value>
        [DataMember(Name="versions", EmitDefaultValue=false)]
        public List<OrderVersionResponse> Versions { get; set; }

        /// <summary>
        /// The total count of unacknowledged orders for the specified enterprise unit id
        /// </summary>
        /// <value>The total count of unacknowledged orders for the specified enterprise unit id</value>
        [DataMember(Name="totalResults", EmitDefaultValue=false)]
        public long? TotalResults { get; set; }

        /// <summary>
        /// The total number of pages
        /// </summary>
        /// <value>The total number of pages</value>
        [DataMember(Name="totalPages", EmitDefaultValue=false)]
        public int? TotalPages { get; set; }

        /// <summary>
        /// The page number of the response
        /// </summary>
        /// <value>The page number of the response</value>
        [DataMember(Name="pageNumber", EmitDefaultValue=false)]
        public int? PageNumber { get; set; }

        /// <summary>
        /// Last page indicator
        /// </summary>
        /// <value>Last page indicator</value>
        [DataMember(Name="lastPage", EmitDefaultValue=false)]
        public bool? LastPage { get; set; }

        /// <summary>
        /// The organization that originally created the order
        /// </summary>
        /// <value>The organization that originally created the order</value>
        [DataMember(Name="sourceOrganization", EmitDefaultValue=false)]
        public string SourceOrganization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderVersionsResponse {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Versions: ").Append(Versions).Append("\n");
            sb.Append("  TotalResults: ").Append(TotalResults).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  LastPage: ").Append(LastPage).Append("\n");
            sb.Append("  SourceOrganization: ").Append(SourceOrganization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderVersionsResponse);
        }

        /// <summary>
        /// Returns true if OrderVersionsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderVersionsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderVersionsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.Versions == input.Versions ||
                    this.Versions != null &&
                    this.Versions.SequenceEqual(input.Versions)
                ) && 
                (
                    this.TotalResults == input.TotalResults ||
                    (this.TotalResults != null &&
                    this.TotalResults.Equals(input.TotalResults))
                ) && 
                (
                    this.TotalPages == input.TotalPages ||
                    (this.TotalPages != null &&
                    this.TotalPages.Equals(input.TotalPages))
                ) && 
                (
                    this.PageNumber == input.PageNumber ||
                    (this.PageNumber != null &&
                    this.PageNumber.Equals(input.PageNumber))
                ) && 
                (
                    this.LastPage == input.LastPage ||
                    (this.LastPage != null &&
                    this.LastPage.Equals(input.LastPage))
                ) && 
                (
                    this.SourceOrganization == input.SourceOrganization ||
                    (this.SourceOrganization != null &&
                    this.SourceOrganization.Equals(input.SourceOrganization))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.Versions != null)
                    hashCode = hashCode * 59 + this.Versions.GetHashCode();
                if (this.TotalResults != null)
                    hashCode = hashCode * 59 + this.TotalResults.GetHashCode();
                if (this.TotalPages != null)
                    hashCode = hashCode * 59 + this.TotalPages.GetHashCode();
                if (this.PageNumber != null)
                    hashCode = hashCode * 59 + this.PageNumber.GetHashCode();
                if (this.LastPage != null)
                    hashCode = hashCode * 59 + this.LastPage.GetHashCode();
                if (this.SourceOrganization != null)
                    hashCode = hashCode * 59 + this.SourceOrganization.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
