/* 
 * order
 *
 * Enables omni-channel persistence and interaction for selling contexts.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace FraudAPI.Model.Order
{
    /// <summary>
    /// VehicleData
    /// </summary>
    [DataContract]
    public partial class VehicleData :  IEquatable<VehicleData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleData" /> class.
        /// </summary>
        /// <param name="Make">The vehicle&#39;s make.</param>
        /// <param name="Model">The vehicle&#39;s model.</param>
        /// <param name="Year">The vehicle&#39;s year.</param>
        /// <param name="Color">The vehicle&#39;s color.</param>
        /// <param name="LicensePlate">The vehicle&#39;s license plate.</param>
        public VehicleData(string Make = default(string), string Model = default(string), string Year = default(string), string Color = default(string), string LicensePlate = default(string))
        {
            this.Make = Make;
            this.Model = Model;
            this.Year = Year;
            this.Color = Color;
            this.LicensePlate = LicensePlate;
        }
        
        /// <summary>
        /// The vehicle&#39;s make
        /// </summary>
        /// <value>The vehicle&#39;s make</value>
        [DataMember(Name="make", EmitDefaultValue=false)]
        public string Make { get; set; }

        /// <summary>
        /// The vehicle&#39;s model
        /// </summary>
        /// <value>The vehicle&#39;s model</value>
        [DataMember(Name="model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// The vehicle&#39;s year
        /// </summary>
        /// <value>The vehicle&#39;s year</value>
        [DataMember(Name="year", EmitDefaultValue=false)]
        public string Year { get; set; }

        /// <summary>
        /// The vehicle&#39;s color
        /// </summary>
        /// <value>The vehicle&#39;s color</value>
        [DataMember(Name="color", EmitDefaultValue=false)]
        public string Color { get; set; }

        /// <summary>
        /// The vehicle&#39;s license plate
        /// </summary>
        /// <value>The vehicle&#39;s license plate</value>
        [DataMember(Name="licensePlate", EmitDefaultValue=false)]
        public string LicensePlate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VehicleData {\n");
            sb.Append("  Make: ").Append(Make).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  LicensePlate: ").Append(LicensePlate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VehicleData);
        }

        /// <summary>
        /// Returns true if VehicleData instances are equal
        /// </summary>
        /// <param name="input">Instance of VehicleData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Make == input.Make ||
                    (this.Make != null &&
                    this.Make.Equals(input.Make))
                ) && 
                (
                    this.Model == input.Model ||
                    (this.Model != null &&
                    this.Model.Equals(input.Model))
                ) && 
                (
                    this.Year == input.Year ||
                    (this.Year != null &&
                    this.Year.Equals(input.Year))
                ) && 
                (
                    this.Color == input.Color ||
                    (this.Color != null &&
                    this.Color.Equals(input.Color))
                ) && 
                (
                    this.LicensePlate == input.LicensePlate ||
                    (this.LicensePlate != null &&
                    this.LicensePlate.Equals(input.LicensePlate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Make != null)
                    hashCode = hashCode * 59 + this.Make.GetHashCode();
                if (this.Model != null)
                    hashCode = hashCode * 59 + this.Model.GetHashCode();
                if (this.Year != null)
                    hashCode = hashCode * 59 + this.Year.GetHashCode();
                if (this.Color != null)
                    hashCode = hashCode * 59 + this.Color.GetHashCode();
                if (this.LicensePlate != null)
                    hashCode = hashCode * 59 + this.LicensePlate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
